### ISSUE TITLE
issue when running extrautilities on a server

### ISSUE THREAD

**Issue by masterbal111** [rwtema/extrautilities_old_issues#186]
Hi, I believe Extra Utilities is causing my server to crash on startup. For some reason this doesn't happen when I load my mod-pack on a client but I've read that this is normal for the kind of error I get.
I am almost 100% sure that Extra Utilities is causing this crash since it is one of the last mods I added and whenever I remove It, It works again. I also read somewhere that it could be a bug with extrautilities in combination with equivalent exchange 3 but even when I delete EE3, the issue still persists.

Here is my crash-log: http://pastebin.com/e1MF49s6

As you can see I have extrautils-1.0.3c, Minecraft 1.6.4 and forge 9.11.1.965. I am aware that the modpack I'm running is pretty big and contains some mods that are considered WIP but aside from this issue it have been working pretty good. And as I said before it works perfectly when running on a client even with extrautils.

Note: this is actually a copy-paste from my post on the forum, I thought it'd be a good idea to post it here too

**Comment by iconmaster5326** [comment]
I can replicate this issue, but with my mod AetherCraft instead. I have had this error reported: https://github.com/iconmaster5326/AetherCraft/issues/23

**Comment by rwtema** [comment]
Please read the readme. I am not developing for 1.6.4.

In any case this is not my issue. The issue is that "dynamicpotions"  and "aetherConduit" are calling client-side code in getRenderType() (which is a server-side method).

**Comment by iconmaster5326** [comment]
What? Oh, the report given to me didn't specify MC version, but now I can assume the report was for 1.6.4. Since I'm not developing for 1.6 either, I can only assume (hope?) this bug is fixed in 1.7. Sorry for bugging you!

And on another note, why on earth would getRenderType ever be used on the server?

**Comment by AlTech98** [comment]
sorry, i forgot to say the mc version
is:
minecraft 1.7.10
forge 10.13.0.1187
last version of AetherCraft and XU

**Comment by iconmaster5326** [comment]
So it's not quite fixed, then. I was afraid of that.

**Comment by rwtema** [comment]
getRenderType should really be called getStructureType. It's used by many things, such as entities using it to determine pathing (over slabs and such). It's also used by the lead to determine if a block is a fence post that can be tied to.

In any case - still not an Extra Utilities issue.
